<template>
  <main class="aurora-layout">

    <!-- Ambient Aurora Background -->
    <div class="ambient-background">
      <div class="glow glow-1"></div>
      <div class="glow glow-2"></div>
      <div class="glow glow-3"></div>
      <div class="noise-texture"></div>
    </div>

    <!-- Center Glass Panel -->
    <section class="glass-panel">

      <!-- Left Side: Branding -->
      <div class="panel-left">
        <div class="brand-container">
          <div class="logo-mark">
            <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M12 2L2 22H22L12 2Z" stroke="url(#paint0_linear)" stroke-width="1.5" stroke-linejoin="round"/>
              <path d="M12 10L6 22H18L12 10Z" stroke="url(#paint1_linear)" stroke-width="1.5" stroke-linejoin="round"/>
              <defs>
                <linearGradient id="paint0_linear" x1="12" y1="2" x2="12" y2="22" gradientUnits="userSpaceOnUse">
                  <stop stop-color="#FFFFFF"/>
                  <stop offset="1" stop-color="#FFFFFF" stop-opacity="0"/>
                </linearGradient>
                <linearGradient id="paint1_linear" x1="12" y1="10" x2="12" y2="22" gradientUnits="userSpaceOnUse">
                  <stop stop-color="#8A93A6"/>
                  <stop offset="1" stop-color="#8A93A6" stop-opacity="0"/>
                </linearGradient>
              </defs>
            </svg>
          </div>
          <h1>Athenaeum Orbis</h1>
          <p>Secure knowledge access layer.</p>
        </div>

        <div class="system-status">
          <span class="status-dot"></span>
          All systems operational
        </div>
      </div>

      <!-- Right Side: Authentication -->
      <div class="panel-right">
        <div class="auth-wrapper">

          <div class="step-header">
            <h2>{{ currentStep === 1 ? 'Welcome back' : 'Two-Step Verification' }}</h2>
            <p class="subtitle">
              {{ currentStep === 1 ? 'Please enter your credentials to continue.' : 'Enter the code generated by your authenticator app.' }}
            </p>
          </div>

          <transition name="fade-slide" mode="out-in">

            <!-- PRIMARY LOGIN -->
            <form v-if="currentStep !== 3" class="premium-form" @submit.prevent="verifyPassword">

              <div class="input-stack">
                <div class="input-field">
                  <label for="identity">Identity</label>
                  <div class="input-box">
                    <span class="prefix">ATH</span>
                    <input
                      id="identity"
                      v-model="identityDigits"
                      type="text"
                      inputmode="text"
                      name="athenaeum_identity"
                      autocomplete="username"
                      autocapitalize="characters"
                      spellcheck="false"
                      maxlength="5"
                      placeholder="user_id"
                      :disabled="loading"
                      @input="sanitizeIdentity"
                    />
                  </div>
                </div>

                <div class="input-field">
                  <label for="password">Password</label>
                  <div class="input-box">
                    <input
                      id="password"
                      v-model="passkey"
                      :type="showPassword ? 'text' : 'password'"
                      name="athenaeum_passkey"
                      autocomplete="current-password"
                      placeholder="••••••••••••"
                      :disabled="loading"
                    />
                    <button
                      type="button"
                      class="visibility-toggle"
                      @click="showPassword = !showPassword"
                      aria-label="Toggle password visibility"
                    >
                      <svg v-if="!showPassword" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                        <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/>
                        <circle cx="12" cy="12" r="3"/>
                      </svg>
                      <svg v-else viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                        <path d="M17.94 17.94A10.07 10.07 0 0112 20c-7 0-11-8-11-8a18.45 18.45 0 015.06-5.94M9.9 4.24A9.12 9.12 0 0112 4c7 0 11 8 11 8a18.5 18.5 0 01-2.16 3.19m-6.72-1.07a3 3 0 11-4.24-4.24M1 1l22 22"/>
                      </svg>
                    </button>
                  </div>
                </div>
              </div>

              <div class="form-actions-row">
                <label class="premium-checkbox">
                  <input v-model="rememberMe" type="checkbox" />
                  <div class="checkbox-indicator">
                    <svg viewBox="0 0 14 10" fill="none">
                      <path d="M1 5L5 9L13 1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                  </div>
                  <span>Remember device</span>
                </label>
              </div>

              <div v-if="errorMessage" class="error-toast">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <circle cx="12" cy="12" r="10"/>
                  <line x1="12" y1="8" x2="12" y2="12"/>
                  <line x1="12" y1="16" x2="12.01" y2="16"/>
                </svg>
                {{ errorMessage }}
              </div>

              <button type="submit" class="primary-btn" :disabled="loading || !identityDigits || !passkey">
                <span class="btn-text">{{ loading ? 'Authenticating...' : 'Sign In' }}</span>
                <span class="btn-glow"></span>
              </button>
            </form>

            <!-- 2FA VERIFICATION -->
            <form v-else class="premium-form" @submit.prevent="verifyTwoFA">

              <div class="input-stack">
                <div class="input-field">
                  <label for="otp">Authentication Code</label>
                  <div class="input-box otp-box">
                    <input
                      id="otp"
                      v-model="tokenPin"
                      class="otp-input"
                      type="text"
                      inputmode="numeric"
                      autocomplete="one-time-code"
                      maxlength="6"
                      placeholder="------"
                      :disabled="loading"
                      @input="sanitizeOtp"
                    />
                  </div>
                </div>
              </div>

              <div v-if="errorMessage" class="error-toast">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <circle cx="12" cy="12" r="10"/>
                  <line x1="12" y1="8" x2="12" y2="12"/>
                  <line x1="12" y1="16" x2="12.01" y2="16"/>
                </svg>
                {{ errorMessage }}
              </div>

              <div class="button-group">
                <button type="submit" class="primary-btn" :disabled="loading || tokenPin.length !== 6">
                  <span class="btn-text">{{ loading ? 'Verifying...' : 'Verify Code' }}</span>
                  <span class="btn-glow"></span>
                </button>

                <button type="button" class="ghost-btn" :disabled="loading" @click="returnToLogin">
                  Return to login
                </button>
              </div>
            </form>

          </transition>
        </div>
      </div>
    </section>
  </main>
</template>

<script setup lang="ts">
import { ref } from "vue"
import { useRouter } from "vue-router"
import { useAuthStore } from "@/stores/auth"

const router = useRouter()
const authStore = useAuthStore()

const API_BASE = import.meta.env.VITE_API_URL || "http://127.0.0.1:8000"

const currentStep = ref(1)

const identityDigits = ref("")
const passkey = ref("")
const tokenPin = ref("")

const temp2faToken = ref<string | null>(null)

const loading = ref(false)
const errorMessage = ref("")

const rememberMe = ref(true)
const showPassword = ref(false)

function sanitizeIdentity() {
  identityDigits.value = identityDigits.value
    .replace(/[^a-zA-Z0-9]/g, "")
    .toUpperCase()
    .slice(0, 5)
}

function sanitizeOtp() {
  tokenPin.value = tokenPin.value
    .replace(/\D/g, "")
    .slice(0, 6)
}

async function verifyPassword() {
  errorMessage.value = ""

  if (!identityDigits.value) {
    errorMessage.value = "Identity is required."
    return
  }

  if (!passkey.value) {
    errorMessage.value = "Password is required."
    return
  }

  loading.value = true

  try {
    const operatorId = `ATH${identityDigits.value}`

    const response = await fetch(`${API_BASE}/token`, {
      method: "POST",
      credentials: "include",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: new URLSearchParams({
        username: operatorId,
        password: passkey.value,
        remember_me: rememberMe.value ? "true" : "false",
      }),
    })

    const data = await response.json().catch(() => ({}))

    if (!response.ok) {
      if (
        response.status === 401 &&
        (data?.detail === "2FA verification required" || data?.twofa_required === true)
      ) {
        temp2faToken.value =
          data?.temp_token ||
          data?.temporary_token ||
          data?.token ||
          null

        currentStep.value = 3
        return
      }

      throw new Error(
        data?.detail ||
        data?.message ||
        "Authentication failed."
      )
    }

    if (
      data?.detail === "2FA verification required" ||
      data?.twofa_required === true
    ) {
      temp2faToken.value =
        data?.temp_token ||
        data?.temporary_token ||
        data?.token ||
        null

      currentStep.value = 3
      return
    }

    const token =
      data?.access_token ||
      data?.access ||
      data?.token

    if (!token) {
      throw new Error(
        "Authentication succeeded but no access token was returned."
      )
    }

    const user =
      data?.user ||
      data?.operator || {
        id: data?.user_id || operatorId,
        username: operatorId,
        name: data?.name || operatorId,
        role: data?.role || "User",
      }

    if (data?.csrf_token) {
      localStorage.setItem("csrf_token", data.csrf_token)
    }

    authStore.login({ access_token: token }, user)
    await router.push("/dashboard")
  } catch (error: any) {
    errorMessage.value =
      error?.message ||
      "Sign in failed. Please check credentials."
  } finally {
    loading.value = false
  }
}

async function verifyTwoFA() {
  errorMessage.value = ""

  if (tokenPin.value.length !== 6) {
    errorMessage.value = "Code must be 6 digits."
    return
  }

  loading.value = true

  try {
    let response: Response

    if (temp2faToken.value) {
      response = await fetch(`${API_BASE}/login/verify-2fa`, {
        method: "POST",
        credentials: "include",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          temp_token: temp2faToken.value,
          token: tokenPin.value,
          remember_me: rememberMe.value,
        }),
      })
    } else {
      response = await fetch(`${API_BASE}/token`, {
        method: "POST",
        credentials: "include",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
        },
        body: new URLSearchParams({
          username: `ATH${identityDigits.value}`,
          password: passkey.value,
          otp_code: tokenPin.value,
          remember_me: rememberMe.value ? "true" : "false",
        }),
      })
    }

    const data = await response.json().catch(() => ({}))

    if (!response.ok) {
      throw new Error(
        data?.detail ||
        data?.message ||
        "Verification failed."
      )
    }

    const token =
      data?.access_token ||
      data?.access ||
      data?.token

    if (!token) {
      throw new Error(
        "Verification succeeded but no access token was returned."
      )
    }

    const operatorId = `ATH${identityDigits.value}`

    const user =
      data?.user ||
      data?.operator || {
        id: data?.user_id || operatorId,
        username: operatorId,
        name: data?.name || operatorId,
        role: data?.role || "User",
      }

    if (data?.csrf_token) {
      localStorage.setItem("csrf_token", data.csrf_token)
    }

    authStore.login({ access_token: token }, user)
    await router.push("/dashboard")
  } catch (error: any) {
    errorMessage.value =
      error?.message ||
      "Invalid verification code."
  } finally {
    loading.value = false
  }
}

function returnToLogin() {
  currentStep.value = 1
  tokenPin.value = ""
  temp2faToken.value = null
  errorMessage.value = ""
}
</script>

<style scoped>
@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap');

:global(body) {
  margin: 0;
  background-color: #0A0A0C;
  color: #FFFFFF;
  font-family: 'Plus Jakarta Sans', -apple-system, sans-serif;
  -webkit-font-smoothing: antialiased;
}

/* =========================================================
   Layout
   ========================================================= */

.aurora-layout {
  position: relative;
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 24px;
  overflow: hidden;
}

/* =========================================================
   Ambient Background
   ========================================================= */

.ambient-background {
  position: absolute;
  inset: 0;
  z-index: 0;
  overflow: hidden;
  background: #0A0A0C;
}

.glow {
  position: absolute;
  border-radius: 50%;
  filter: blur(100px);
  opacity: 0.4;
  animation: drift 20s infinite alternate ease-in-out;
}

.glow-1 {
  width: 50vw;
  height: 50vw;
  background: #0047FF;
  top: -10%;
  left: -10%;
}

.glow-2 {
  width: 40vw;
  height: 40vw;
  background: #8A2BE2;
  bottom: -10%;
  right: -5%;
  animation-delay: -5s;
}

.glow-3 {
  width: 30vw;
  height: 30vw;
  background: #00F0FF;
  top: 40%;
  left: 30%;
  animation-delay: -10s;
}

.noise-texture {
  position: absolute;
  inset: 0;
  opacity: 0.04;
  background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.8' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E");
  pointer-events: none;
}

@keyframes drift {
  0% {
    transform: translate(0, 0) scale(1);
  }

  100% {
    transform: translate(5%, 5%) scale(1.1);
  }
}

/* =========================================================
   Center Panel
   ========================================================= */

.glass-panel {
  position: relative;
  z-index: 10;
  width: 100%;
  max-width: 900px;
  min-height: 560px;
  background: rgba(20, 20, 24, 0.4);
  backdrop-filter: blur(40px);
  -webkit-backdrop-filter: blur(40px);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 24px;
  display: flex;
  box-shadow:
    0 30px 60px rgba(0, 0, 0, 0.4),
    inset 0 1px 0 rgba(255, 255, 255, 0.1);
  overflow: hidden;
}

/* =========================================================
   Left Panel
   ========================================================= */

.panel-left {
  flex: 1;
  padding: 48px;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  border-right: 1px solid rgba(255, 255, 255, 0.05);
  background: linear-gradient(
    135deg,
    rgba(255, 255, 255, 0.03) 0%,
    transparent 100%
  );
}

.logo-mark {
  width: 40px;
  height: 40px;
  margin-bottom: 24px;
}

.brand-container h1 {
  font-size: 24px;
  font-weight: 500;
  letter-spacing: -0.02em;
  margin: 0 0 8px 0;
  color: #FFFFFF;
}

.brand-container p {
  font-size: 14px;
  color: #8A93A6;
  margin: 0;
}

.system-status {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 13px;
  color: #8A93A6;
}

.status-dot {
  width: 8px;
  height: 8px;
  background-color: #00F0FF;
  border-radius: 50%;
  box-shadow: 0 0 12px rgba(0, 240, 255, 0.6);
}

/* =========================================================
   Right Panel
   ========================================================= */

.panel-right {
  flex: 1;
  padding: 48px;
  display: flex;
  align-items: center;
}

.auth-wrapper {
  width: 100%;
  max-width: 340px;
  margin: 0 auto;
}

.step-header {
  margin-bottom: 32px;
}

.step-header h2 {
  font-size: 24px;
  font-weight: 600;
  letter-spacing: -0.02em;
  margin: 0 0 8px 0;
}

.subtitle {
  font-size: 14px;
  color: #8A93A6;
  margin: 0;
  line-height: 1.5;
}

/* =========================================================
   Forms
   ========================================================= */

.premium-form {
  display: flex;
  flex-direction: column;
  gap: 24px;
}

.input-stack {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.input-field {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.input-field label {
  font-size: 13px;
  font-weight: 500;
  color: #8A93A6;
}

/* =========================================================
   Input Containers
   ========================================================= */

.input-box {
  display: flex;
  align-items: center;
  background: rgba(255, 255, 255, 0.03);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 12px;
  padding: 4px 16px;
  position: relative;
  overflow: hidden;
  transition:
    background 0.2s ease,
    border-color 0.2s ease,
    box-shadow 0.2s ease;
}

.input-box:focus-within {
  background: rgba(255, 255, 255, 0.06);
  border-color: rgba(255, 255, 255, 0.2);
  box-shadow: 0 0 0 4px rgba(255, 255, 255, 0.02);
}

.prefix {
  flex-shrink: 0;
  margin-right: 8px;
  font-size: 15px;
  font-weight: 600;
  color: #8A93A6;
  user-select: none;
}

/* =========================================================
   Inputs / Chromium Autofill Fix
   ========================================================= */

/* The .input-box is the ONLY visible input surface. */
.input-box input {
  flex: 1;
  width: 100%;
  min-width: 0;
  padding: 10px 0;

  background: transparent !important;
  background-color: transparent !important;
  background-image: none !important;

  border: none !important;
  outline: none !important;
  box-shadow: none !important;

  color: #FFFFFF !important;
  -webkit-text-fill-color: #FFFFFF !important;
  caret-color: #FFFFFF !important;

  font-family: inherit;
  font-size: 15px;

  -webkit-appearance: none !important;
  appearance: none !important;
}

.input-box input:focus,
.input-box input:active,
.input-box input:focus-visible {
  background: transparent !important;
  background-color: transparent !important;
  background-image: none !important;
  box-shadow: none !important;
  outline: none !important;
}

/*
 * Chromium/Brave credential autofill.
 *
 * Do NOT use the old 1000px inset white shadow here.
 * That shadow was creating the visible rectangular surface
 * inside the rounded .input-box.
 *
 * The .input-box itself supplies the visible background.
 */
.input-box input:-webkit-autofill,
.input-box input:-webkit-autofill:hover,
.input-box input:-webkit-autofill:focus,
.input-box input:-webkit-autofill:active {
  background: transparent !important;
  background-color: transparent !important;
  background-image: none !important;

  color: #FFFFFF !important;
  -webkit-text-fill-color: #FFFFFF !important;
  caret-color: #FFFFFF !important;

  border: none !important;
  outline: none !important;

  -webkit-box-shadow: none !important;
  box-shadow: none !important;

  -webkit-appearance: none !important;
  appearance: none !important;

  transition: background-color 99999s ease-out 0s !important;
}

.input-box input::placeholder {
  color: #4A5160;
  opacity: 1;
}

/* Chromium credential/password decoration */
.input-box input::-webkit-credentials-auto-fill-button {
  display: none !important;
}

.input-box input::-webkit-textfield-decoration-container {
  display: none !important;
}

/* Microsoft / Edge */
.input-box input::-ms-reveal,
.input-box input::-ms-clear {
  display: none !important;
}

/* =========================================================
   OTP
   ========================================================= */

.otp-box input {
  text-align: center;
  font-size: 20px;
  letter-spacing: 6px;
  font-weight: 600;
}

/* =========================================================
   Password Visibility Button
   ========================================================= */

.visibility-toggle {
  flex: 0 0 auto;
  width: 32px;
  height: 32px;
  margin-left: 8px;
  padding: 0;

  display: flex;
  align-items: center;
  justify-content: center;

  background: transparent;
  border: none;

  color: #5C6370;
  cursor: pointer;

  transition: color 0.2s;
}

.visibility-toggle svg {
  width: 18px;
  height: 18px;
  display: block;
}

.visibility-toggle:hover {
  color: #FFFFFF;
}

/* =========================================================
   Checkbox
   ========================================================= */

.form-actions-row {
  margin-top: -8px;
}

.premium-checkbox {
  display: inline-flex;
  align-items: center;
  gap: 10px;
  cursor: pointer;
  font-size: 13px;
  color: #8A93A6;
  user-select: none;
}

.premium-checkbox input {
  display: none;
}

.checkbox-indicator {
  width: 18px;
  height: 18px;
  border: 1px solid rgba(255, 255, 255, 0.15);
  border-radius: 6px;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.2s;
  background: rgba(255, 255, 255, 0.02);
}

.checkbox-indicator svg {
  width: 10px;
  height: 10px;
  color: #000;
  opacity: 0;
  transform: scale(0.8);
  transition: all 0.2s;
}

.premium-checkbox input:checked + .checkbox-indicator {
  background: #FFFFFF;
  border-color: #FFFFFF;
}

.premium-checkbox input:checked + .checkbox-indicator svg {
  opacity: 1;
  transform: scale(1);
}

/* =========================================================
   Errors
   ========================================================= */

.error-toast {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 12px 16px;
  background: rgba(255, 51, 102, 0.1);
  border: 1px solid rgba(255, 51, 102, 0.2);
  border-radius: 12px;
  color: #FF7B93;
  font-size: 13px;
  line-height: 1.4;
}

.error-toast svg {
  width: 16px;
  height: 16px;
  flex-shrink: 0;
}

/* =========================================================
   Buttons
   ========================================================= */

.primary-btn {
  position: relative;
  width: 100%;
  background: #FFFFFF;
  color: #0A0A0C;
  border: none;
  border-radius: 12px;
  padding: 14px;
  font-family: inherit;
  font-size: 14px;
  font-weight: 600;
  cursor: pointer;
  overflow: hidden;
  transition: transform 0.2s;
}

.primary-btn:hover:not(:disabled) {
  transform: translateY(-1px);
}

.primary-btn:active:not(:disabled) {
  transform: translateY(1px);
}

.primary-btn:disabled {
  background: rgba(255, 255, 255, 0.1);
  color: rgba(255, 255, 255, 0.3);
  cursor: not-allowed;
}

.btn-text {
  position: relative;
  z-index: 2;
}

.btn-glow {
  position: absolute;
  top: 0;
  left: -100%;
  width: 100%;
  height: 100%;
  background: linear-gradient(
    90deg,
    transparent,
    rgba(255, 255, 255, 0.4),
    transparent
  );
  z-index: 1;
  transition: 0.5s;
}

.primary-btn:hover:not(:disabled) .btn-glow {
  left: 100%;
}

.button-group {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.ghost-btn {
  background: transparent;
  border: 1px solid transparent;
  color: #8A93A6;
  padding: 12px;
  border-radius: 12px;
  font-family: inherit;
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}

.ghost-btn:hover:not(:disabled) {
  background: rgba(255, 255, 255, 0.05);
  color: #FFFFFF;
}

/* =========================================================
   Transitions
   ========================================================= */

.fade-slide-enter-active,
.fade-slide-leave-active {
  transition:
    opacity 0.3s ease,
    transform 0.3s ease;
}

.fade-slide-enter-from {
  opacity: 0;
  transform: translateX(10px);
}

.fade-slide-leave-to {
  opacity: 0;
  transform: translateX(-10px);
}

/* =========================================================
   Responsive
   ========================================================= */

@media (max-width: 860px) {
  .glass-panel {
    flex-direction: column;
    min-height: auto;
  }

  .panel-left {
    padding: 32px;
    border-right: none;
    border-bottom: 1px solid rgba(255, 255, 255, 0.05);
    background: linear-gradient(
      180deg,
      rgba(255, 255, 255, 0.03) 0%,
      transparent 100%
    );
  }

  .system-status {
    display: none;
  }

  .panel-right {
    padding: 32px;
  }
}
</style>
